"""create reservation schema

Revision ID: 1330edc40d13
Revises: 
Create Date: 2026-10-02 15:07:41.710177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1330edc40d13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('per_user_limit', sa.Integer(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.CheckConstraint('per_user_limit > 0', name='ck_shows_per_user_limit_positive'),
    sa.CheckConstraint('price_paise >= 0', name='ck_shows_price_non_negative'),
    sa.CheckConstraint('total_seats > 0', name='ck_shows_total_seats_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint("status IN ('confirmed', 'cancelled')", name='ck_reservations_status'),
    sa.CheckConstraint('amount_paise >= 0', name='ck_reservations_amount_non_negative'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'user_id', 'idempotency_key', name='uq_reservation_idempotency')
    )
    op.create_index('ix_reservations_show_user_status', 'reservations', ['show_id', 'user_id', 'status'], unique=False)
    op.create_table('show_seats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reserved_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint("status IN ('available', 'held', 'confirmed')", name='ck_show_seats_status'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'seat_number', name='uq_show_seat')
    )
    op.create_index('ix_show_seats_show_status', 'show_seats', ['show_id', 'status'], unique=False)
    op.create_table('show_user_counters',
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('seat_count >= 0', name='ck_show_user_counter_non_negative'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('show_id', 'user_id')
    )
    op.create_table('reservation_seats',
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['show_seats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id', 'seat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_seats')
    op.drop_table('show_user_counters')
    op.drop_index('ix_show_seats_show_status', table_name='show_seats')
    op.drop_table('show_seats')
    op.drop_index('ix_reservations_show_user_status', table_name='reservations')
    op.drop_table('reservations')
    op.drop_table('shows')
    # ### end Alembic commands ###
